name: Main

on: pull_request

permissions: write-all

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: htunnicliff/replace-comment-html@main
        with:
          selector: "h1 > span"
          html: "<span>worlds!</span>"
