name: Main

on: pull_request

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: htunnicliff/replace-comment-html@main
        with:
          selector: "h1"
          html: "<h1>hello <span>worlds</span></h1>"
