name: Main

on: pull_request

permissions:
  issues: write

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: htunnicliff/replace-comment-html@main
        with:
          selector: "h1"
          html: "<h1>See you later!</h1>"
